name: rtu_wimpillay
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ãconos y utilidades bÃ¡sicas
  cupertino_icons: ^1.0.8
  provider: ^6.1.1

  # ðŸ”¥ Firebase (versiones compatibles)
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

  # ðŸ”‘ Login con Google
  google_sign_in: ^6.2.1

  # ðŸ“± EscÃ¡ner QR y cÃ¡mara
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
